export const hostingCategories = [
  {
    id: 'shared',
    name: 'Web Hosting',
    badge: 'MOST POPULAR FOR WEBSITES',
    tagline: 'High-speed NVMe shared cloud hosting for business websites and blogs.',
    plans: [
      {
        id: 'shared-starter',
        name: 'Starter Web',
        tag: 'Best for 1 website',
        priceMonthlyINR: 99,
        priceYearlyINR: 79,
        priceUSD: 1.99,
        priceEUR: 1.85,
        features: [
          '1 Website',
          '20 GB Ultra NVMe Storage',
          'Free SSL Certificate (Lifetime)',
          '5 Professional Email Accounts',
          'Unmetered Bandwidth',
          '1-Click WordPress Installer',
          '99.9% Uptime Guarantee',
          '24/7 Technical Support',
          'Weekly Automated Backups',
        ],
        popular: false,
      },
      {
        id: 'shared-plus',
        name: 'Business Plus',
        tag: 'Recommended for growing businesses',
        priceMonthlyINR: 199,
        priceYearlyINR: 159,
        priceUSD: 3.99,
        priceEUR: 3.69,
        features: [
          'Unlimited Websites',
          '100 GB Ultra NVMe Storage',
          'Free Domain Name (1st Year)',
          'Free Wildcard SSL Certificate',
          'Unlimited Business Emails',
          'Unmetered Fast Bandwidth',
          'LiteSpeed / Redis Caching',
          'Daily Automated Cloud Backups',
          'Free Website & Email Migration',
          'Priority 24/7 Support',
        ],
        popular: true,
      },
      {
        id: 'shared-pro',
        name: 'Enterprise Pro',
        tag: 'Max speed & dedicated resources',
        priceMonthlyINR: 399,
        priceYearlyINR: 329,
        priceUSD: 6.99,
        priceEUR: 6.49,
        features: [
          'Unlimited Websites & Subdomains',
          'Unmetered NVMe SSD Storage',
          'Free Domain Name (1st Year)',
          'Free Dedicated IP Address',
          'Free Wildcard SSL & DDoS Shield',
          'Unlimited Business Emails',
          'Premium LiteSpeed Web Server',
          'Real-time Malware Scanning & Cleanup',
          'Daily Backups with 1-Click Restore',
          'VIP 24/7 Ticket & WhatsApp Support',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'vps',
    name: 'Cloud VPS',
    badge: 'FOR APPS & HIGH TRAFFIC',
    tagline: 'Dedicated CPU, RAM, NVMe storage and full root access for custom applications.',
    plans: [
      {
        id: 'vps-2core',
        name: 'Cloud VPS 2C',
        tag: '2 vCPU / 4GB RAM',
        priceMonthlyINR: 799,
        priceYearlyINR: 699,
        priceUSD: 9.99,
        priceEUR: 9.25,
        features: [
          '2 vCPU High-Speed Cores',
          '4 GB Dedicated RAM',
          '80 GB Pure NVMe Storage',
          '2 TB Monthly Bandwidth',
          '1 Dedicated IPv4 Address',
          'Full Root & SSH Access',
          'Ubuntu / Debian / AlmaLinux / CentOS',
          'KVM Cloud Virtualization',
          '24/7 Server Hardware Monitoring',
        ],
        popular: false,
      },
      {
        id: 'vps-4core',
        name: 'Cloud VPS 4C',
        tag: '4 vCPU / 8GB RAM',
        priceMonthlyINR: 1499,
        priceYearlyINR: 1299,
        priceUSD: 18.99,
        priceEUR: 17.50,
        features: [
          '4 vCPU High-Speed Cores',
          '8 GB Dedicated RAM',
          '160 GB Pure NVMe Storage',
          '4 TB Monthly Bandwidth',
          '1 Dedicated IPv4 Address',
          'Full Root & SSH Access',
          '1-Click OS & Docker Stacks',
          'Custom Firewall & DDoS Defense',
          'Automated Snapshot Backups',
          '24/7 Managed Server Support',
        ],
        popular: true,
      },
      {
        id: 'vps-8core',
        name: 'Cloud VPS 8C',
        tag: '8 vCPU / 16GB RAM',
        priceMonthlyINR: 2999,
        priceYearlyINR: 2599,
        priceUSD: 36.99,
        priceEUR: 34.00,
        features: [
          '8 vCPU High-Speed Cores',
          '16 GB Dedicated RAM',
          '320 GB Pure NVMe Storage',
          '8 TB Monthly Bandwidth',
          '2 Dedicated IPv4 Addresses',
          'Full Root, IPMI & SSH Access',
          'Private Networking / VPC Ready',
          'Enterprise DDoS Mitigation',
          'Dedicated Account Engineer',
          'Custom Load Balancer Support',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'email',
    name: 'Business Email',
    badge: 'BRAND IDENTITY & SECURITY',
    tagline: 'Professional business email @yourdomain.com with webmail, mobile sync, and spam protection.',
    plans: [
      {
        id: 'email-basic',
        name: 'Standard Email',
        tag: '5 Business Mailboxes',
        priceMonthlyINR: 149,
        priceYearlyINR: 119,
        priceUSD: 2.49,
        priceEUR: 2.29,
        features: [
          '5 Custom Business Mailboxes',
          '10 GB Storage per Mailbox',
          'Webmail, Outlook, iOS & Android Sync',
          'SpamAssassin & Antivirus Filters',
          'Custom DKIM, SPF & DMARC Setup',
          'Calendar & Contacts Sharing',
          '99.9% Guaranteed Mail Delivery',
        ],
        popular: false,
      },
      {
        id: 'email-pro',
        name: 'Unlimited Mail Suite',
        tag: 'Unlimited Team Mailboxes',
        priceMonthlyINR: 349,
        priceYearlyINR: 299,
        priceUSD: 4.99,
        priceEUR: 4.59,
        features: [
          'Unlimited Custom Business Mailboxes',
          '50 GB Storage per Mailbox',
          'Google Workspace / M365 Integration',
          'Advanced AI Spam & Phishing Shield',
          'Automated Daily Email Archiving',
          'Custom Domain DNS Management',
          'Priority 24/7 Email Setup Support',
        ],
        popular: true,
      },
    ],
  },
  {
    id: 'wordpress',
    name: 'WordPress & E-Com',
    badge: 'OPTIMIZED FOR SPEED',
    tagline: 'Managed WordPress and WooCommerce hosting with automated caching and 1-click staging.',
    plans: [
      {
        id: 'wp-starter',
        name: 'WP Launch',
        tag: 'Fast WordPress site',
        priceMonthlyINR: 149,
        priceYearlyINR: 119,
        priceUSD: 2.99,
        priceEUR: 2.75,
        features: [
          '1 WordPress Website',
          '30 GB Fast NVMe Storage',
          'Pre-installed WordPress & Plugins',
          'Free SSL & Cloudflare CDN',
          'Built-in LiteSpeed Cache',
          'Automated Core & Plugin Updates',
          '24/7 WP Technical Support',
        ],
        popular: false,
      },
      {
        id: 'wp-ecommerce',
        name: 'WooCommerce Pro',
        tag: 'Online stores & payments',
        priceMonthlyINR: 349,
        priceYearlyINR: 289,
        priceUSD: 5.99,
        priceEUR: 5.49,
        features: [
          'Unlimited WordPress Stores',
          '100 GB NVMe Storage',
          'Pre-configured WooCommerce & Cart',
          'Payment Gateway Integration Support',
          'Staging Environment for Testing',
          'Daily Cloud Backups + Instant Restore',
          'Free Domain + Free Wildcard SSL',
          'Priority E-Commerce Expert Support',
        ],
        popular: true,
      },
    ],
  },
];

export const hostingAddons = [
  { name: 'Free Domain Name', description: 'Free .com / .in / .org domain with 1-year annual hosting plan', icon: 'Globe' },
  { name: 'Free Website Migration', description: 'Our engineers will migrate your existing website & emails with zero downtime', icon: 'ArrowRightLeft' },
  { name: 'Free Lifetime SSL', description: 'Automated 256-bit SSL certificates for all your domains & subdomains', icon: 'ShieldCheck' },
  { name: '24/7 Real Human Support', description: 'Direct assistance via Phone, WhatsApp, and Tickets whenever you need help', icon: 'Headphones' },
];
