import { hostingCategories } from './hostingData.js';

// One catalogue drives the mega menu, footer, product pages, sitemap and prerender.
export const tlds = [
  { ext: '.com', price: 799, renew: 1099, tag: 'POPULAR' },
  { ext: '.in', price: 499, renew: 699, tag: 'BEST FOR INDIA' },
  { ext: '.co.in', price: 349, renew: 499, tag: 'VALUE' },
  { ext: '.org', price: 899, renew: 1199, tag: 'TRUSTED' },
  { ext: '.net', price: 949, renew: 1249, tag: 'TECH' },
  { ext: '.io', price: 2499, renew: 3999, tag: 'STARTUPS' },
  { ext: '.co', price: 699, renew: 2399, tag: 'GLOBAL' },
  { ext: '.online', price: 199, renew: 2499, tag: 'OFFER' },
  { ext: '.store', price: 249, renew: 3999, tag: 'E-COMMERCE' },
  { ext: '.tech', price: 399, renew: 3999, tag: 'DEVELOPERS' },
];

export const inr = (value) => `₹${Number(value).toLocaleString('en-IN')}`;

export const domainSearchUrl = (query, tld = '.com') => {
  const name = query.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/\/.*$/, '') || 'mycompany';
  const domain = name.includes('.') ? name : `${name}${tld}`;
  return `/contact?service=domain-hosting&domain=${encodeURIComponent(domain)}`;
};

const fromHosting = (categoryId) => hostingCategories
  .find((category) => category.id === categoryId)
  .plans.map((plan) => ({
    name: plan.name,
    tag: plan.tag,
    price: plan.priceYearlyINR,
    unit: '/mo',
    note: `Billed yearly · ${inr(plan.priceMonthlyINR)}/mo on monthly billing`,
    features: plan.features,
    popular: plan.popular,
  }));

export const productGroups = [
  { id: 'domains', label: 'Domains', blurb: 'Find, register and protect the name your business will be known by.' },
  { id: 'hosting', label: 'Hosting', blurb: 'Fast NVMe hosting with free SSL, email, backups and 24/7 help.' },
  { id: 'servers', label: 'Servers', blurb: 'Cloud VPS and dedicated servers with root access and full control.' },
  { id: 'email-security', label: 'Email & Security', blurb: 'Professional email, SSL certificates, malware protection and backups.' },
  { id: 'websites', label: 'Websites', blurb: 'Build it yourself or let our designers create it for you.' },
  { id: 'marketing', label: 'SEO & Marketing', blurb: 'Get found on Google and turn visitors into customers.' },
];

export const productPages = {
  // ── Domains ────────────────────────────────────────────────
  'product:domain-registration': {
    group: 'domains',
    icon: 'Globe',
    path: '/domains/domain-registration',
    breadcrumbLabel: 'Domain Registration',
    navDesc: '.com, .in, .co.in and 50+ extensions',
    eyebrow: 'DOMAIN REGISTRATION',
    heading: 'Register the perfect domain name for your business',
    summary: 'Search and register .com, .in, .co.in, .org, .net and new extensions with free DNS management, email forwarding and domain lock included.',
    title: 'Domain Name Registration in India – .com, .in from ₹349 | Zexton',
    description: 'Register .com, .in, .co.in, .org, .net and new domain extensions with free DNS management, domain forwarding, theft protection and 24/7 support from Zexton.',
    searchIntent: 'domain registration India',
    topics: ['domain registration', 'buy domain name India', '.in domain', '.com domain', 'cheap domain names'],
    priceFrom: 349,
    showDomainSearch: true,
    showTldTable: true,
    features: [
      ['Free DNS management', 'Edit A, AAAA, CNAME, MX, TXT, SRV and CAA records from a simple panel with fast propagation.'],
      ['Domain & email forwarding', 'Point your domain to any website and forward emails like sales@yourbrand.com to your inbox.'],
      ['Domain theft protection', 'Registrar lock blocks unauthorised transfers. Transfer codes are only issued to the verified owner.'],
      ['Auto-renew reminders', 'Renewal reminders at 30, 15 and 7 days, with optional auto-renew so your name never lapses.'],
      ['Easy hosting connection', 'Connect to Zexton hosting, email or any third-party platform (Shopify, Wix, Google Sites) in minutes.'],
      ['Full ownership', 'The domain is registered in your name and business details — you remain the legal registrant.'],
    ],
    steps: [
      ['Search', 'Type your business name and compare available extensions.'],
      ['Add to order', 'Pick 1–10 years, add privacy protection or hosting if needed.'],
      ['Verify', 'Confirm your registrant email so the domain is legally yours.'],
      ['Go live', 'Point DNS to your website and set up professional email.'],
    ],
    faqs: [
      ['How long does domain registration take?', 'Most domains are active within minutes of payment. DNS changes can take up to 24–48 hours to be visible worldwide, though usually much sooner.'],
      ['Should I choose .com or .in?', 'Choose .in or .co.in if your customers are mainly in India — it signals a local business. Choose .com for international reach. Many businesses register both to protect their brand.'],
      ['Can I register a domain for more than one year?', 'Yes. Domains can be registered for 1 to 10 years. Longer registrations protect your name and avoid yearly renewal risk.'],
      ['What documents are required?', 'Accurate registrant name, email, phone and address are required by registry rules. Some country extensions have extra eligibility checks.'],
      ['What happens if I forget to renew?', 'Most domains enter a grace period after expiry where you can still renew at the normal price, followed by a redemption period with a higher restore fee. Enable auto-renew to avoid this.'],
    ],
    relatedRoutes: ['product:domain-transfer', 'product:web-hosting', 'product:business-email', 'product:ssl-certificates'],
  },
  'product:domain-transfer': {
    group: 'domains',
    icon: 'ArrowRightLeft',
    path: '/domains/domain-transfer',
    breadcrumbLabel: 'Domain Transfer',
    navDesc: 'Move your domain to Zexton + 1 year free extension',
    eyebrow: 'DOMAIN TRANSFER',
    heading: 'Transfer your domain to Zexton — keep everything, add a year',
    summary: 'Move your existing domain from any registrar in a few steps. Your website and email stay online during the transfer, and the registration is extended by one year.',
    title: 'Domain Transfer to Zexton – Free 1-Year Extension | Zexton',
    description: 'Transfer your .com, .in, .org or .net domain to Zexton with zero downtime, a 1-year extension, free DNS management and help from our support team.',
    searchIntent: 'transfer domain to another registrar',
    topics: ['domain transfer', 'transfer domain India', 'EPP code', 'change domain registrar'],
    priceFrom: 499,
    features: [
      ['1-year extension included', 'Every transfer adds one year to your current expiry date — you do not lose the time already paid for.'],
      ['Zero downtime', 'Existing DNS records are preserved, so your website and email keep working throughout.'],
      ['Guided by our team', 'We help you unlock the domain, get the EPP/auth code and approve the transfer.'],
      ['All domains in one place', 'Manage domains, hosting, email and SSL from a single Zexton account and invoice.'],
    ],
    steps: [
      ['Unlock', 'Remove the registrar lock at your current provider.'],
      ['Get the code', 'Request the EPP / authorisation code.'],
      ['Start transfer', 'Enter the domain and code with Zexton and pay the transfer fee.'],
      ['Approve', 'Approve the email confirmation — transfers complete in 5–7 days.'],
    ],
    faqs: [
      ['Can any domain be transferred?', 'A domain must be at least 60 days old, not transferred in the last 60 days, unlocked, and not expired or in redemption.'],
      ['Will my website go down during the transfer?', 'No. The nameservers and DNS records stay the same, so visitors and email are not affected.'],
      ['How long does a transfer take?', 'Usually 5 to 7 days for generic domains like .com. Some .in transfers complete faster once approved.'],
      ['What is an EPP code?', 'It is a password-like authorisation code your current registrar issues to prove you own the domain and approve the move.'],
    ],
    relatedRoutes: ['product:domain-registration', 'product:dns-management', 'product:web-hosting', 'support'],
  },
  'product:domain-privacy': {
    group: 'domains',
    icon: 'EyeOff',
    path: '/domains/domain-privacy',
    breadcrumbLabel: 'Domain Privacy & Protection',
    navDesc: 'Hide WHOIS details, block spam and hijacking',
    eyebrow: 'DOMAIN PRIVACY & PROTECTION',
    heading: 'Keep your personal details out of public WHOIS',
    summary: 'Privacy protection replaces your phone, email and address in the public WHOIS database with masked details, cutting spam calls and phishing aimed at domain owners.',
    title: 'Domain Privacy Protection & WHOIS Masking | Zexton',
    description: 'Protect your name, email, phone and address from public WHOIS lookups with Zexton domain privacy, theft protection and registrar lock.',
    searchIntent: 'domain privacy protection',
    topics: ['domain privacy', 'WHOIS privacy', 'domain theft protection', 'registrar lock'],
    priceFrom: 199,
    priceUnit: '/yr',
    features: [
      ['WHOIS masking', 'Your contact details are replaced with privacy-service details in public lookups.'],
      ['Spam filtering', 'Messages sent to the masked email are filtered before being forwarded to you.'],
      ['Registrar lock', 'Blocks unauthorised transfers and changes to critical domain settings.'],
      ['Ownership unchanged', 'You remain the legal owner; privacy only affects what the public can see.'],
    ],
    faqs: [
      ['Is domain privacy available for .in domains?', 'Registry policy for some country-code domains limits what can be shown publicly. Our team will confirm what is available for your extension.'],
      ['Can people still contact me?', 'Yes. Legitimate messages sent to the masked contact address are forwarded to you.'],
      ['Does privacy affect SEO?', 'No. Search engines do not rank sites based on WHOIS visibility.'],
    ],
    relatedRoutes: ['product:domain-registration', 'product:dns-management', 'product:website-security', 'support'],
  },
  'product:dns-management': {
    group: 'domains',
    icon: 'Network',
    path: '/domains/dns-management',
    breadcrumbLabel: 'DNS Management',
    navDesc: 'Free DNS hosting, forwarding and records',
    eyebrow: 'DNS MANAGEMENT',
    heading: 'Fast, reliable DNS that connects your domain to everything',
    summary: 'Point your domain at websites, email providers and apps with free anycast DNS, domain forwarding, and help configuring SPF, DKIM and DMARC for email deliverability.',
    title: 'Free DNS Management, Domain Forwarding & Email Records | Zexton',
    description: 'Manage A, CNAME, MX, TXT, SRV and CAA records, set up domain forwarding, and configure SPF, DKIM and DMARC with free Zexton DNS management.',
    searchIntent: 'DNS management service',
    topics: ['DNS management', 'domain forwarding', 'SPF DKIM DMARC', 'MX records'],
    priceFrom: 0,
    features: [
      ['All record types', 'A, AAAA, CNAME, MX, TXT, SRV, CAA and NS records with sensible defaults.'],
      ['Domain forwarding', '301/302 redirects and masked forwarding to any URL.'],
      ['Email authentication', 'We help set up SPF, DKIM and DMARC so your emails do not land in spam.'],
      ['Third-party connections', 'Guided records for Google Workspace, Microsoft 365, Shopify, Zoho and more.'],
    ],
    faqs: [
      ['Is DNS management free?', 'Yes, DNS management is included free with every domain registered or transferred to Zexton.'],
      ['How long do DNS changes take?', 'Changes on our nameservers apply almost instantly, but cached records elsewhere can take up to the record TTL (often 1–4 hours) to update.'],
      ['Can I use Cloudflare or other nameservers?', 'Yes. You can point your domain to any nameservers while keeping it registered with Zexton.'],
    ],
    relatedRoutes: ['product:domain-registration', 'product:business-email', 'product:web-hosting', 'support'],
  },

  // ── Hosting ────────────────────────────────────────────────
  'product:web-hosting': {
    group: 'hosting',
    icon: 'Server',
    path: '/hosting/web-hosting',
    breadcrumbLabel: 'Linux Web Hosting',
    navDesc: 'NVMe shared hosting with cPanel & free SSL',
    eyebrow: 'LINUX WEB HOSTING',
    heading: 'Fast, secure Linux web hosting for every website',
    summary: 'NVMe SSD shared hosting with cPanel, LiteSpeed caching, free SSL, business email and daily backups — ideal for business websites, blogs and portfolios.',
    title: 'Linux Web Hosting India with cPanel & Free SSL from ₹79/mo | Zexton',
    description: 'Affordable Linux shared web hosting in India with NVMe storage, cPanel, free SSL, business email, LiteSpeed cache, daily backups and 24/7 support.',
    searchIntent: 'web hosting India',
    topics: ['web hosting India', 'Linux hosting', 'cPanel hosting', 'cheap web hosting', 'shared hosting'],
    plans: fromHosting('shared'),
    features: [
      ['NVMe SSD storage', 'Up to 10× faster read speeds than SATA SSD for quicker page loads.'],
      ['cPanel control panel', 'Manage files, databases, email, domains and SSL from the industry-standard panel.'],
      ['LiteSpeed & caching', 'Server-level caching makes WordPress and PHP sites noticeably faster.'],
      ['Free SSL certificates', 'Auto-renewing HTTPS for every domain and subdomain.'],
      ['1-click installers', 'Install WordPress, Joomla, Drupal, Magento and 400+ apps in one click.'],
      ['Free migration', 'We move your website, databases and emails from your old host for free.'],
    ],
    specs: [
      ['PHP versions', '7.4 – 8.3 (selectable per site)'],
      ['Databases', 'MySQL / MariaDB, phpMyAdmin'],
      ['Access', 'FTP, SFTP, SSH (Business plans), Git'],
      ['Web server', 'LiteSpeed Enterprise'],
      ['Security', 'Imunify360 firewall, malware scanning'],
      ['Backups', 'Weekly or daily with 1-click restore'],
    ],
    faqs: [
      ['Which hosting plan should I choose?', 'Starter suits a single small website. Business Plus is best for most businesses running several sites or WordPress with moderate traffic. Enterprise Pro adds more resources, a dedicated IP and priority support.'],
      ['Can I upgrade later?', 'Yes. Upgrade anytime from your account; the difference is prorated and there is no downtime.'],
      ['Do you offer a money-back guarantee?', 'Hosting plans come with a 30-day money-back guarantee. Domain registrations are non-refundable once registered.'],
      ['Is email included?', 'Yes, every plan includes professional email accounts on your own domain with webmail and IMAP/POP/SMTP access.'],
      ['Where are the servers located?', 'Servers are hosted in Tier-III data centres. Contact us if you need a specific region for latency or compliance.'],
    ],
    relatedRoutes: ['product:wordpress-hosting', 'product:cloud-hosting', 'product:vps-hosting', 'product:domain-registration'],
  },
  'product:windows-hosting': {
    group: 'hosting',
    icon: 'AppWindow',
    path: '/hosting/windows-hosting',
    breadcrumbLabel: 'Windows Hosting',
    navDesc: 'ASP.NET, .NET Core & MSSQL with Plesk',
    eyebrow: 'WINDOWS HOSTING',
    heading: 'Windows hosting for ASP.NET, .NET Core and MSSQL',
    summary: 'Run ASP.NET, .NET Core, classic ASP and MSSQL applications on Windows Server with the Plesk control panel, free SSL and business email.',
    title: 'Windows Hosting India – ASP.NET, .NET Core & MSSQL | Zexton',
    description: 'Windows shared hosting with Plesk, ASP.NET, .NET Core, MSSQL databases, free SSL, business email and 24/7 expert support from Zexton.',
    searchIntent: 'Windows hosting India',
    topics: ['Windows hosting', 'ASP.NET hosting', '.NET Core hosting', 'MSSQL hosting', 'Plesk hosting'],
    plans: [
      { name: 'Windows Starter', tag: '1 website', price: 149, unit: '/mo', note: 'Billed yearly', features: ['1 Website', '20 GB NVMe Storage', '1 MSSQL Database (1 GB)', 'ASP.NET 4.8 & .NET 6/8', 'Plesk Control Panel', 'Free SSL Certificate', '5 Email Accounts', '24/7 Support'] },
      { name: 'Windows Business', tag: 'Growing apps', price: 299, unit: '/mo', note: 'Billed yearly', popular: true, features: ['5 Websites', '75 GB NVMe Storage', '5 MSSQL Databases (5 GB)', 'ASP.NET & .NET Core', 'IIS URL Rewrite & Web Deploy', 'Free SSL for all sites', '50 Email Accounts', 'Daily Backups', 'Priority Support'] },
      { name: 'Windows Pro', tag: 'High traffic', price: 549, unit: '/mo', note: 'Billed yearly', features: ['Unlimited Websites', '150 GB NVMe Storage', 'Unlimited MSSQL Databases', 'Dedicated App Pools', 'Free Dedicated IP', 'Unlimited Email', 'Daily Backups + Restore', 'Malware Protection', 'VIP Support'] },
    ],
    features: [
      ['Latest .NET runtimes', '.NET Framework 4.8 and modern .NET (6, 8) with isolated application pools.'],
      ['MSSQL databases', 'Microsoft SQL Server with remote management via SSMS.'],
      ['Plesk control panel', 'Manage IIS sites, databases, email, DNS and SSL from one dashboard.'],
      ['Web Deploy', 'Publish straight from Visual Studio using Web Deploy or FTP.'],
    ],
    faqs: [
      ['Do I need Windows hosting for my site?', 'Only if your application uses ASP.NET, .NET, classic ASP or MSSQL. PHP, WordPress and most CMS platforms run best on Linux hosting.'],
      ['Can I use MySQL on Windows hosting?', 'Yes, MySQL is available alongside MSSQL on Windows plans.'],
      ['Can I deploy from Visual Studio?', 'Yes. Web Deploy publishing profiles are available in Plesk.'],
    ],
    relatedRoutes: ['product:web-hosting', 'product:vps-hosting', 'product:cloud-hosting', 'service:custom-software-development'],
  },
  'product:wordpress-hosting': {
    group: 'hosting',
    icon: 'Zap',
    path: '/hosting/wordpress-hosting',
    breadcrumbLabel: 'WordPress Hosting',
    navDesc: 'Managed WordPress & WooCommerce',
    eyebrow: 'MANAGED WORDPRESS HOSTING',
    heading: 'WordPress hosting tuned for speed, security and sales',
    summary: 'Pre-installed WordPress with LiteSpeed cache, automatic updates, staging, malware protection and WooCommerce-ready plans for online stores.',
    title: 'Managed WordPress & WooCommerce Hosting India | Zexton',
    description: 'Fast managed WordPress hosting with pre-installed WordPress, LiteSpeed cache, automatic updates, staging, free SSL, CDN and WooCommerce-ready plans.',
    searchIntent: 'WordPress hosting India',
    topics: ['WordPress hosting', 'WooCommerce hosting', 'managed WordPress', 'fast WordPress hosting'],
    plans: fromHosting('wordpress'),
    features: [
      ['WordPress pre-installed', 'Your site is ready to log into the moment your account is created.'],
      ['LiteSpeed Cache', 'Page, object and browser caching configured for WordPress out of the box.'],
      ['Automatic updates', 'Core, theme and plugin updates with safe rollback.'],
      ['Staging site', 'Test changes on a copy before pushing them live.'],
      ['Malware protection', 'Firewall rules and scanning tuned for common WordPress attacks.'],
      ['Free CDN', 'Static assets served from edge locations close to your visitors.'],
    ],
    faqs: [
      ['Can you migrate my existing WordPress site?', 'Yes, free. Our team moves files, database and emails and checks everything before you switch DNS.'],
      ['Is WooCommerce supported?', 'Yes. WooCommerce Pro is configured for stores with cart caching exceptions, staging and daily backups.'],
      ['Do I get admin access?', 'Yes, full WordPress admin plus cPanel, SFTP and database access.'],
    ],
    relatedRoutes: ['product:web-hosting', 'product:website-design', 'product:website-security', 'product:ssl-certificates'],
  },
  'product:cloud-hosting': {
    group: 'hosting',
    icon: 'Cloud',
    path: '/hosting/cloud-hosting',
    breadcrumbLabel: 'Cloud Hosting',
    navDesc: 'Dedicated resources, cPanel simplicity',
    eyebrow: 'CLOUD HOSTING',
    heading: 'Cloud hosting with dedicated resources and cPanel simplicity',
    summary: 'Guaranteed CPU and RAM with isolated containers, so a busy neighbour never slows your site — without having to manage a server yourself.',
    title: 'Cloud Hosting India – Dedicated Resources, cPanel | Zexton',
    description: 'Managed cloud hosting with guaranteed CPU and RAM, isolated resources, NVMe storage, cPanel, free SSL, daily backups and instant scaling.',
    searchIntent: 'cloud hosting India',
    topics: ['cloud hosting', 'managed cloud hosting', 'scalable hosting', 'high traffic hosting'],
    plans: [
      { name: 'Cloud Start', tag: '2 CPU · 4 GB RAM', price: 699, unit: '/mo', note: 'Billed yearly', features: ['2 Dedicated CPU Cores', '4 GB RAM', '100 GB NVMe Storage', '10 Websites', 'cPanel & LiteSpeed', 'Free SSL + CDN', 'Daily Backups', '24/7 Support'] },
      { name: 'Cloud Business', tag: '4 CPU · 8 GB RAM', price: 1299, unit: '/mo', note: 'Billed yearly', popular: true, features: ['4 Dedicated CPU Cores', '8 GB RAM', '200 GB NVMe Storage', 'Unlimited Websites', 'Dedicated IP', 'Redis Object Cache', 'Daily Backups + Restore', 'Malware Protection', 'Priority Support'] },
      { name: 'Cloud Scale', tag: '8 CPU · 16 GB RAM', price: 2499, unit: '/mo', note: 'Billed yearly', features: ['8 Dedicated CPU Cores', '16 GB RAM', '400 GB NVMe Storage', 'Unlimited Websites', 'Dedicated IP', 'Advanced WAF', 'Hourly Snapshots', 'Uptime Monitoring', 'VIP Support'] },
    ],
    features: [
      ['Guaranteed resources', 'CPU and RAM are reserved for your account, not shared.'],
      ['Instant scaling', 'Upgrade CPU, RAM or storage in minutes when traffic grows.'],
      ['Fully managed', 'We handle the OS, security patches, web server and monitoring.'],
      ['Isolated accounts', 'Container isolation keeps other customers’ traffic from affecting you.'],
    ],
    faqs: [
      ['How is cloud hosting different from shared hosting?', 'Shared hosting pools resources across many accounts. Cloud hosting reserves CPU and RAM for you, giving predictable speed under load.'],
      ['How is it different from a VPS?', 'Cloud hosting is fully managed with cPanel; a VPS gives you root access and you (or our managed plan) administer the server.'],
      ['Can I scale during a sale or campaign?', 'Yes. Resources can be upgraded quickly and scaled back later.'],
    ],
    relatedRoutes: ['product:web-hosting', 'product:vps-hosting', 'product:wordpress-hosting', 'product:dedicated-servers'],
  },
  'product:reseller-hosting': {
    group: 'hosting',
    icon: 'Users',
    path: '/hosting/reseller-hosting',
    breadcrumbLabel: 'Reseller Hosting',
    navDesc: 'White-label hosting with WHM for agencies',
    eyebrow: 'RESELLER HOSTING',
    heading: 'Start your own hosting business under your brand',
    summary: 'White-label reseller hosting with WHM and cPanel for web designers, agencies and freelancers who want to host client websites and earn recurring revenue.',
    title: 'White-Label Reseller Hosting with WHM & cPanel | Zexton',
    description: 'Reseller hosting for agencies and web designers: WHM, cPanel accounts, white-label nameservers, free SSL, NVMe storage and 24/7 support.',
    searchIntent: 'reseller hosting India',
    topics: ['reseller hosting', 'white label hosting', 'WHM reseller', 'agency hosting'],
    plans: [
      { name: 'Reseller Silver', tag: '25 cPanel accounts', price: 899, unit: '/mo', note: 'Billed yearly', features: ['25 cPanel Accounts', '100 GB NVMe Storage', 'WHM Control Panel', 'White-label Nameservers', 'Free SSL for all Clients', 'Unmetered Bandwidth', '24/7 Support'] },
      { name: 'Reseller Gold', tag: '50 cPanel accounts', price: 1599, unit: '/mo', note: 'Billed yearly', popular: true, features: ['50 cPanel Accounts', '250 GB NVMe Storage', 'WHM Control Panel', 'White-label Nameservers', 'Free SSL + Imunify360', 'Daily Backups', 'Free Client Migrations', 'Priority Support'] },
      { name: 'Reseller Platinum', tag: 'Unlimited accounts', price: 2999, unit: '/mo', note: 'Billed yearly', features: ['Unlimited cPanel Accounts', '500 GB NVMe Storage', 'WHM + Billing Integration', 'Private Nameservers', 'Dedicated IP', 'Daily Backups', 'Free Client Migrations', 'VIP Support'] },
    ],
    features: [
      ['Your brand, not ours', 'Custom nameservers and a white-label cPanel so clients see your agency.'],
      ['WHM control', 'Create packages, set limits and manage every client account.'],
      ['Recurring revenue', 'Bundle hosting with your design and maintenance services.'],
      ['We handle servers', 'Hardware, OS, security and backups are managed by Zexton.'],
    ],
    faqs: [
      ['Do my clients know Zexton is the host?', 'No. Nameservers, cPanel branding and billing can all carry your brand.'],
      ['Can I set my own prices?', 'Yes. You decide packages and pricing for your clients.'],
      ['Who supports my clients?', 'You support your clients; Zexton supports you 24/7 for anything server-related.'],
    ],
    relatedRoutes: ['product:web-hosting', 'product:cloud-hosting', 'product:vps-hosting', 'contact'],
  },

  // ── Servers ────────────────────────────────────────────────
  'product:vps-hosting': {
    group: 'servers',
    icon: 'Cpu',
    path: '/servers/vps-hosting',
    breadcrumbLabel: 'VPS Hosting',
    navDesc: 'Linux & Windows KVM VPS with root access',
    eyebrow: 'CLOUD VPS HOSTING',
    heading: 'NVMe cloud VPS with full root access',
    summary: 'KVM virtual servers with dedicated vCPU, RAM and NVMe storage. Choose Linux or Windows, self-managed or fully managed, and scale whenever you need.',
    title: 'VPS Hosting India – Linux & Windows KVM VPS from ₹699/mo | Zexton',
    description: 'Linux and Windows KVM VPS hosting with NVMe storage, dedicated IPv4, full root access, DDoS protection, snapshots and optional managed support.',
    searchIntent: 'VPS hosting India',
    topics: ['VPS hosting India', 'Linux VPS', 'Windows VPS', 'KVM VPS', 'NVMe VPS', 'managed VPS'],
    plans: fromHosting('vps'),
    features: [
      ['KVM virtualisation', 'True hardware virtualisation with guaranteed resources and your own kernel.'],
      ['Root / Administrator access', 'Install any software, configure the firewall and run Docker or custom stacks.'],
      ['Choice of OS', 'Ubuntu, Debian, AlmaLinux, Rocky Linux or Windows Server (licence extra).'],
      ['Optional control panels', 'Add cPanel, Plesk, CyberPanel or aaPanel at checkout.'],
      ['Snapshots & backups', 'Take snapshots before risky changes and restore in minutes.'],
      ['Managed option', 'Let our engineers handle patching, security hardening and monitoring.'],
    ],
    specs: [
      ['Virtualisation', 'KVM'],
      ['Storage', 'Enterprise NVMe SSD, RAID-10'],
      ['Network', '1 Gbps port, DDoS protection'],
      ['IP', '1 dedicated IPv4 + IPv6'],
      ['Operating systems', 'Ubuntu, Debian, AlmaLinux, Rocky, Windows Server'],
      ['Access', 'SSH / RDP, VNC console'],
    ],
    faqs: [
      ['Managed or self-managed — which do I need?', 'Self-managed suits developers comfortable with Linux administration. Managed VPS adds security updates, hardening, monitoring and help with server issues.'],
      ['Can I install Docker?', 'Yes. KVM supports Docker, Kubernetes distributions and custom kernels.'],
      ['Is a Windows VPS available?', 'Yes. Windows Server can be selected at checkout; the licence is billed monthly.'],
      ['Can I upgrade without reinstalling?', 'Yes. CPU, RAM and storage upgrades require only a reboot.'],
    ],
    relatedRoutes: ['product:dedicated-servers', 'product:cloud-hosting', 'service:it-support', 'service:cloud-modernization'],
  },
  'product:dedicated-servers': {
    group: 'servers',
    icon: 'HardDrive',
    path: '/servers/dedicated-servers',
    breadcrumbLabel: 'Dedicated Servers',
    navDesc: 'Bare-metal power, managed or unmanaged',
    eyebrow: 'DEDICATED SERVERS',
    heading: 'Bare-metal dedicated servers for demanding workloads',
    summary: 'An entire physical server for your business — dedicated CPU, RAM and NVMe disks, high bandwidth, root access and optional fully-managed support.',
    title: 'Dedicated Servers India – Managed Bare-Metal Hosting | Zexton',
    description: 'Dedicated bare-metal servers with Intel Xeon / AMD EPYC CPUs, NVMe RAID storage, high bandwidth, DDoS protection, IPMI and managed support.',
    searchIntent: 'dedicated server India',
    topics: ['dedicated server', 'bare metal server', 'managed dedicated server', 'high performance server'],
    plans: [
      { name: 'Entry Server', tag: 'Intel Xeon · 8 cores', price: 6999, unit: '/mo', features: ['Intel Xeon E-2236 · 6C/12T', '32 GB DDR4 ECC RAM', '2 × 512 GB NVMe (RAID-1)', '10 TB Bandwidth', '1 Gbps Port', '3 Dedicated IPv4', 'IPMI / KVM Access', 'Linux or Windows'] },
      { name: 'Business Server', tag: 'AMD EPYC · 16 cores', price: 12999, unit: '/mo', popular: true, features: ['AMD EPYC 7302P · 16C/32T', '64 GB DDR4 ECC RAM', '2 × 1 TB NVMe (RAID-1)', '20 TB Bandwidth', '1 Gbps Port', '5 Dedicated IPv4', 'DDoS Protection', 'Optional cPanel / Plesk', 'Managed Support Available'] },
      { name: 'Enterprise Server', tag: 'Dual CPU · 32+ cores', price: 24999, unit: '/mo', features: ['2 × Intel Xeon Silver · 32C/64T', '128 GB DDR4 ECC RAM', '4 × 1.92 TB NVMe (RAID-10)', 'Unmetered 1 Gbps', '10 Gbps Port Option', '8 Dedicated IPv4', 'Advanced DDoS Protection', 'Fully Managed', 'Dedicated Account Manager'] },
    ],
    features: [
      ['100% dedicated hardware', 'No virtualisation overhead and no noisy neighbours.'],
      ['Enterprise components', 'ECC memory, NVMe RAID and redundant power supplies.'],
      ['Out-of-band access', 'IPMI / KVM console to reinstall or recover even when the OS is down.'],
      ['Managed option', 'OS updates, hardening, monitoring, backups and control panel management.'],
      ['Custom builds', 'GPU servers, extra disks or private networking configured on request.'],
    ],
    faqs: [
      ['How long does deployment take?', 'Standard configurations deploy within 24–48 hours after verification. Custom builds may take longer.'],
      ['Can I get a GPU server?', 'Yes. GPU configurations for AI inference and rendering are available on request.'],
      ['What does managed include?', 'OS patching, security hardening, firewall, monitoring, backups, control panel support and help during incidents.'],
    ],
    relatedRoutes: ['product:vps-hosting', 'product:cloud-hosting', 'service:it-support', 'contact'],
  },

  // ── Email & Security ───────────────────────────────────────
  'product:business-email': {
    group: 'email-security',
    icon: 'Mail',
    path: '/email/business-email',
    breadcrumbLabel: 'Business Email',
    navDesc: 'you@yourbusiness.com with spam protection',
    eyebrow: 'PROFESSIONAL BUSINESS EMAIL',
    heading: 'Professional email on your own domain',
    summary: 'Replace free Gmail or Yahoo addresses with you@yourbusiness.com. Secure webmail, mobile sync, calendars and strong spam protection — at a price that fits small teams.',
    title: 'Business Email Hosting India – Email on Your Domain | Zexton',
    description: 'Professional business email on your own domain with webmail, IMAP/POP/SMTP, mobile sync, calendars, anti-spam, anti-virus and free migration.',
    searchIntent: 'business email India',
    topics: ['business email', 'professional email', 'email hosting India', 'custom domain email'],
    plans: fromHosting('email'),
    features: [
      ['Your domain, your brand', 'Every email you send reinforces your business name.'],
      ['Works everywhere', 'Webmail plus Outlook, Apple Mail, Gmail app, Thunderbird, Android and iOS.'],
      ['Spam & virus filtering', 'Multi-layer filtering stops spam, phishing and malicious attachments.'],
      ['Calendars & contacts', 'Shared calendars and address books synced across devices.'],
      ['Deliverability set up', 'SPF, DKIM and DMARC configured so your mail reaches inboxes.'],
      ['Free migration', 'We move existing mailboxes from your current provider.'],
    ],
    faqs: [
      ['Do I need a domain first?', 'Yes. If you do not have one, register it with Zexton and we will connect email automatically.'],
      ['Can I use Gmail or Outlook apps?', 'Yes. Mailboxes work with any IMAP/SMTP client including the Gmail and Outlook mobile apps.'],
      ['Can I add more mailboxes later?', 'Yes. Add or remove mailboxes anytime; billing is adjusted pro-rata.'],
    ],
    relatedRoutes: ['product:google-workspace', 'product:domain-registration', 'product:dns-management', 'product:web-hosting'],
  },
  'product:google-workspace': {
    group: 'email-security',
    icon: 'Briefcase',
    path: '/email/google-workspace-microsoft-365',
    breadcrumbLabel: 'Google Workspace & Microsoft 365',
    navDesc: 'Setup, licensing and migration',
    eyebrow: 'GOOGLE WORKSPACE & MICROSOFT 365',
    heading: 'Google Workspace and Microsoft 365, set up properly',
    summary: 'Get the productivity suite your team already knows — Gmail, Drive and Meet or Outlook, Teams and OneDrive — with licensing, DNS setup and email migration handled by Zexton.',
    title: 'Google Workspace & Microsoft 365 Setup and Migration | Zexton',
    description: 'Buy and set up Google Workspace or Microsoft 365 with domain verification, MX/SPF/DKIM records, user creation and email migration handled by Zexton.',
    searchIntent: 'Google Workspace setup India',
    topics: ['Google Workspace', 'Microsoft 365', 'email migration', 'Office 365 setup'],
    plans: [
      { name: 'Setup & Migration', tag: 'One-time service', price: 2999, unit: ' one-time', note: 'Up to 10 users', features: ['Domain verification', 'MX, SPF, DKIM & DMARC setup', 'User & group creation', 'Mailbox migration (up to 10 users)', 'Mobile & desktop client setup', '30 days post-setup support'] },
      { name: 'Managed Workspace', tag: 'Ongoing admin', price: 99, unit: '/user/mo', note: 'Plus licence cost', popular: true, features: ['Everything in Setup', 'User onboarding / offboarding', 'Security & sharing policies', 'Shared drives & groups', 'Monthly security review', 'Priority support'] },
    ],
    features: [
      ['Licensing guidance', 'We help you choose the right Business Starter/Standard or M365 Basic/Standard plan.'],
      ['Zero lost email', 'Mailboxes, contacts and calendars are migrated before switching MX records.'],
      ['Security baseline', '2-step verification, admin roles and sharing rules configured from day one.'],
    ],
    faqs: [
      ['Is the licence included?', 'Licence fees are billed at Google or Microsoft pricing. Our plans cover setup, migration and administration.'],
      ['Google Workspace or Microsoft 365?', 'Choose Workspace if your team lives in Gmail and Docs; choose Microsoft 365 if you rely on Outlook, Excel and Teams.'],
    ],
    relatedRoutes: ['product:business-email', 'product:dns-management', 'service:it-support', 'contact'],
  },
  'product:ssl-certificates': {
    group: 'email-security',
    icon: 'Lock',
    path: '/security/ssl-certificates',
    breadcrumbLabel: 'SSL Certificates',
    navDesc: 'DV, OV, EV & Wildcard certificates',
    eyebrow: 'SSL CERTIFICATES',
    heading: 'SSL certificates that build trust and protect data',
    summary: 'Encrypt every visit, show the padlock, and avoid “Not Secure” browser warnings. From free DV to Organisation-validated and Wildcard certificates, installed for you.',
    title: 'Buy SSL Certificates India – DV, OV, EV & Wildcard | Zexton',
    description: 'Domain-validated, organisation-validated, EV and wildcard SSL certificates with installation, 256-bit encryption, warranty and 24/7 support from Zexton.',
    searchIntent: 'buy SSL certificate India',
    topics: ['SSL certificate', 'wildcard SSL', 'EV SSL', 'HTTPS certificate'],
    plans: [
      { name: 'Standard DV', tag: 'Blogs & small sites', price: 999, unit: '/yr', features: ['Domain Validation', 'Issued in minutes', '256-bit encryption', 'Covers www + non-www', 'Site seal', 'Free installation'] },
      { name: 'Wildcard DV', tag: 'All subdomains', price: 5999, unit: '/yr', popular: true, features: ['Unlimited subdomains', 'Issued in minutes', '256-bit encryption', 'Unlimited server licences', 'Site seal', 'Free installation'] },
      { name: 'Business OV', tag: 'Verified company', price: 4999, unit: '/yr', features: ['Organisation Validation', 'Company name in certificate', 'Higher trust for payments', 'Warranty included', 'Issued in 1–3 days', 'Free installation'] },
      { name: 'Extended EV', tag: 'Banks & e-commerce', price: 11999, unit: '/yr', features: ['Extended Validation', 'Strictest identity checks', 'Maximum customer trust', 'Highest warranty', 'Issued in 3–5 days', 'Free installation'] },
    ],
    features: [
      ['Required by browsers', 'Chrome and other browsers label non-HTTPS pages as “Not Secure”.'],
      ['Better SEO', 'HTTPS is a confirmed Google ranking signal.'],
      ['Protects payments', 'Card, login and form data are encrypted in transit.'],
      ['Installed for you', 'We generate the CSR, validate and install the certificate.'],
    ],
    faqs: [
      ['Is free SSL enough?', 'Free DV SSL (included with hosting) is enough for most websites. Paid OV/EV certificates verify your company identity and include a warranty — useful for payments and enterprise buyers.'],
      ['What is a wildcard certificate?', 'One certificate that secures yourdomain.com and all first-level subdomains like shop.yourdomain.com and app.yourdomain.com.'],
      ['Can I use it on hosting elsewhere?', 'Yes. We can provide the certificate files and installation help for any server.'],
    ],
    relatedRoutes: ['product:website-security', 'product:website-backup', 'product:web-hosting', 'product:domain-registration'],
  },
  'product:website-security': {
    group: 'email-security',
    icon: 'ShieldCheck',
    path: '/security/website-security',
    breadcrumbLabel: 'Website Security',
    navDesc: 'Malware scan, removal, firewall & DDoS',
    eyebrow: 'WEBSITE SECURITY',
    heading: 'Stop hackers, malware and blacklisting before they cost you',
    summary: 'Daily malware scanning, automatic removal, web application firewall and DDoS protection that keep your website clean, online and trusted by Google.',
    title: 'Website Security, Malware Removal & Firewall (WAF) | Zexton',
    description: 'Protect your website with daily malware scanning, automatic malware removal, web application firewall, DDoS mitigation and blacklist monitoring.',
    searchIntent: 'website malware removal',
    topics: ['website security', 'malware removal', 'web application firewall', 'DDoS protection'],
    plans: [
      { name: 'Scan', tag: 'Detect issues', price: 199, unit: '/mo', features: ['Daily malware scan', 'Blacklist monitoring', 'Email alerts', 'Security report', '1 website'] },
      { name: 'Protect', tag: 'Detect + fix', price: 499, unit: '/mo', popular: true, features: ['Everything in Scan', 'Automatic malware removal', 'Web application firewall', 'Bad-bot blocking', 'Blacklist removal help', '1 website'] },
      { name: 'Shield', tag: 'Business-critical', price: 999, unit: '/mo', features: ['Everything in Protect', 'DDoS mitigation', 'CDN acceleration', 'Virtual patching', 'Priority incident response', '1 website'] },
    ],
    features: [
      ['Malware scanning', 'Files and pages are scanned daily for injected code, backdoors and spam links.'],
      ['Automatic cleanup', 'Known infections are removed automatically; complex cases are handled by our team.'],
      ['Web application firewall', 'Blocks SQL injection, XSS, brute-force logins and known exploits.'],
      ['Blacklist monitoring', 'Get alerted if Google or antivirus vendors flag your domain.'],
    ],
    faqs: [
      ['My site is already hacked — can you help?', 'Yes. Choose Protect or contact support for an emergency cleanup. We remove the malware, patch the entry point and request blacklist review.'],
      ['Does it work with WordPress?', 'Yes, and with most PHP, static and CMS-based websites.'],
    ],
    relatedRoutes: ['product:ssl-certificates', 'product:website-backup', 'product:wordpress-hosting', 'service:it-support'],
  },
  'product:website-backup': {
    group: 'email-security',
    icon: 'DatabaseBackup',
    path: '/security/website-backup',
    breadcrumbLabel: 'Website Backup',
    navDesc: 'Automated daily backups, 1-click restore',
    eyebrow: 'WEBSITE BACKUP',
    heading: 'Automatic backups so one mistake never becomes a disaster',
    summary: 'Daily off-site backups of your files and databases with version history and one-click restore — protection from hacks, bad updates and accidental deletions.',
    title: 'Automated Website & Database Backup with 1-Click Restore | Zexton',
    description: 'Automated daily website and database backups stored off-site with 30–90 day history, one-click restore and malware-safe versions.',
    searchIntent: 'website backup service',
    topics: ['website backup', 'database backup', 'automatic backup', 'disaster recovery'],
    plans: [
      { name: 'Backup 10', tag: '10 GB', price: 149, unit: '/mo', features: ['10 GB off-site storage', 'Daily automatic backups', '30-day history', 'Files + databases', '1-click restore'] },
      { name: 'Backup 50', tag: '50 GB', price: 349, unit: '/mo', popular: true, features: ['50 GB off-site storage', 'Daily automatic backups', '60-day history', 'Files + databases', '1-click restore', 'Malware scanning of backups'] },
      { name: 'Backup 200', tag: '200 GB', price: 899, unit: '/mo', features: ['200 GB off-site storage', 'Twice-daily backups', '90-day history', 'Files + databases', '1-click restore', 'Priority restore support'] },
    ],
    features: [
      ['Off-site storage', 'Backups are stored away from your hosting server in encrypted storage.'],
      ['Version history', 'Restore from any day in your retention window.'],
      ['Granular restore', 'Restore the full site, a single file, or just the database.'],
    ],
    faqs: [
      ['My hosting already has backups — do I need this?', 'Hosting backups protect the server. Independent off-site backups protect you if the server, account or host itself has a problem.'],
    ],
    relatedRoutes: ['product:website-security', 'product:ssl-certificates', 'product:web-hosting', 'product:vps-hosting'],
  },

  // ── Websites ───────────────────────────────────────────────
  'product:website-builder': {
    group: 'websites',
    icon: 'LayoutTemplate',
    path: '/websites/website-builder',
    breadcrumbLabel: 'Website Builder',
    navDesc: 'Drag-and-drop, no coding needed',
    eyebrow: 'WEBSITE BUILDER',
    heading: 'Build your website yourself — no coding needed',
    summary: 'Pick a professionally designed template, customise it with drag-and-drop, and publish a mobile-friendly website on your own domain in an afternoon.',
    title: 'Website Builder – Create a Website Without Coding | Zexton',
    description: 'Drag-and-drop website builder with business templates, mobile-responsive design, free SSL, hosting, SEO tools, WhatsApp button and online store options.',
    searchIntent: 'website builder India',
    topics: ['website builder', 'create website without coding', 'drag and drop website', 'small business website'],
    plans: [
      { name: 'Personal', tag: 'Simple website', price: 149, unit: '/mo', note: 'Billed yearly', features: ['Up to 10 pages', '100+ templates', 'Free SSL + hosting', 'Mobile responsive', 'Contact forms', 'Google Maps & social links'] },
      { name: 'Business', tag: 'Grow your brand', price: 299, unit: '/mo', note: 'Billed yearly', popular: true, features: ['Unlimited pages', 'Free domain (1st year)', 'Blog', 'SEO settings & analytics', 'WhatsApp chat button', 'Business email (1 mailbox)', 'Remove Zexton branding'] },
      { name: 'Online Store', tag: 'Sell online', price: 599, unit: '/mo', note: 'Billed yearly', features: ['Everything in Business', 'Up to 500 products', 'Razorpay / UPI payments', 'Inventory & orders', 'Discount coupons', 'GST-ready invoices'] },
    ],
    features: [
      ['Choose a template', 'Templates for shops, restaurants, clinics, consultants, portfolios and more.'],
      ['Drag-and-drop editing', 'Change text, images, colours and sections visually.'],
      ['Mobile-first', 'Every design adapts automatically to phones and tablets.'],
      ['SEO built-in', 'Edit page titles, descriptions and social previews.'],
    ],
    steps: [
      ['Choose template', 'Start from a design made for your industry.'],
      ['Customise', 'Add your logo, text, photos and colours.'],
      ['Connect domain', 'Use your Zexton domain or one you already own.'],
      ['Publish', 'Go live with free SSL in one click.'],
    ],
    faqs: [
      ['Do I need technical skills?', 'No. If you can use a word processor you can build a site with the builder.'],
      ['Can I switch to a custom-designed website later?', 'Yes. Our design team can rebuild or extend your site whenever you outgrow the builder.'],
    ],
    relatedRoutes: ['product:website-design', 'product:domain-registration', 'product:business-email', 'product:seo-services'],
  },
  'product:website-design': {
    group: 'websites',
    icon: 'Palette',
    path: '/websites/website-design',
    breadcrumbLabel: 'Website Design & Development',
    navDesc: 'Professionally designed business websites',
    eyebrow: 'WEBSITE DESIGN & DEVELOPMENT',
    heading: 'A professionally designed website that wins customers',
    summary: 'Our designers and developers create fast, mobile-friendly, SEO-ready websites for businesses — from a 5-page company site to a custom portal — with hosting and support included.',
    title: 'Website Design & Development Company India – from ₹9,999 | Zexton',
    description: 'Professional website design and development for businesses: responsive design, WordPress or custom code, SEO setup, hosting, SSL and ongoing support.',
    searchIntent: 'website design company India',
    topics: ['website design company', 'website development India', 'business website design', 'WordPress website development'],
    plans: [
      { name: 'Starter Website', tag: '5–7 pages', price: 9999, unit: ' one-time', features: ['5–7 page responsive website', 'Template-based custom design', 'Contact form + WhatsApp button', 'Basic on-page SEO', 'Free domain + 1 yr hosting', 'Delivered in 7–10 days'] },
      { name: 'Business Website', tag: '10–15 pages', price: 24999, unit: ' one-time', popular: true, features: ['10–15 page custom design', 'CMS to edit content yourself', 'Blog & lead-capture forms', 'On-page SEO + speed optimisation', 'Google Analytics & Search Console', 'Free domain, hosting & email (1 yr)', 'Delivered in 2–3 weeks'] },
      { name: 'Professional', tag: 'Custom UI/UX', price: 49999, unit: ' one-time', features: ['Unique UI/UX design', 'Up to 30 pages', 'Advanced animations', 'Multilingual support', 'Integrations (CRM, booking, payments)', 'Priority support for 3 months'] },
      { name: 'Enterprise / Portal', tag: 'Custom application', price: 150000, unit: '+', note: 'Quoted after discovery', features: ['Custom web application', 'Customer or partner portal', 'Role-based access', 'API & ERP integrations', 'Cloud deployment', 'Maintenance SLA'] },
    ],
    features: [
      ['Designed to convert', 'Clear messaging, strong calls-to-action and trust signals on every page.'],
      ['Mobile-first & fast', 'Optimised images, caching and clean code for good Core Web Vitals.'],
      ['SEO-ready', 'Proper headings, meta tags, schema, sitemap and Search Console setup.'],
      ['You own it', 'Full admin access and ownership of the domain, content and code.'],
    ],
    steps: [
      ['Brief', 'Tell us about your business, customers and goals.'],
      ['Design', 'Review the homepage design and request changes.'],
      ['Build', 'We develop all pages, forms and integrations.'],
      ['Launch', 'Go live with hosting, SSL, analytics and training.'],
    ],
    faqs: [
      ['What do I need to provide?', 'Your logo, business details, and any text and photos you have. We can also write content and source images.'],
      ['Can I update the website myself?', 'Yes. Business and higher packages include a CMS so you can edit text, images and blog posts.'],
      ['Do you build e-commerce websites?', 'Yes — see E-commerce Website Development for WooCommerce, Shopify and custom stores.'],
    ],
    relatedRoutes: ['product:ecommerce-website', 'product:website-builder', 'product:seo-services', 'service:web-application-development'],
  },
  'product:ecommerce-website': {
    group: 'websites',
    icon: 'ShoppingCart',
    path: '/websites/ecommerce-website',
    breadcrumbLabel: 'E-commerce Website',
    navDesc: 'Online stores with UPI & card payments',
    eyebrow: 'E-COMMERCE WEBSITE DEVELOPMENT',
    heading: 'Launch an online store that is ready to sell',
    summary: 'WooCommerce, Shopify or custom e-commerce stores with product catalogues, Razorpay/UPI payments, shipping integration, GST invoices and a mobile-first checkout.',
    title: 'E-commerce Website Development India – WooCommerce & Shopify | Zexton',
    description: 'E-commerce website development with WooCommerce, Shopify or custom code, Razorpay/UPI payments, shipping, GST invoicing and hosting from Zexton.',
    searchIntent: 'ecommerce website development India',
    topics: ['ecommerce website development', 'WooCommerce development', 'Shopify store setup', 'online store India'],
    plans: [
      { name: 'Store Launch', tag: 'Up to 50 products', price: 29999, unit: ' one-time', features: ['WooCommerce or Shopify store', 'Up to 50 products uploaded', 'Razorpay / UPI / card payments', 'Shipping & COD setup', 'GST-ready invoices', 'Delivered in 2–3 weeks'] },
      { name: 'Store Growth', tag: 'Up to 500 products', price: 59999, unit: ' one-time', popular: true, features: ['Custom store design', 'Up to 500 products', 'Shiprocket / courier integration', 'Coupons, reviews & wishlists', 'Abandoned-cart emails', 'Speed & SEO optimisation', 'Hosting & SSL (1 yr)'] },
      { name: 'Custom Commerce', tag: 'Marketplace / B2B', price: 150000, unit: '+', note: 'Quoted after discovery', features: ['Multi-vendor marketplace', 'B2B pricing & quotes', 'ERP / inventory sync', 'Mobile app option', 'Custom checkout flows', 'Dedicated support'] },
    ],
    features: [
      ['Indian payments', 'Razorpay, PayU, Cashfree, UPI, cards, net banking and COD.'],
      ['Shipping ready', 'Integrations with Shiprocket and major couriers.'],
      ['Fast checkout', 'Mobile-first checkout designed to reduce abandoned carts.'],
      ['Manage it yourself', 'Add products, process orders and run offers from your dashboard.'],
    ],
    faqs: [
      ['WooCommerce or Shopify?', 'WooCommerce gives full control and no platform commission; Shopify is simpler to run but has a monthly subscription. We recommend based on your catalogue and team.'],
      ['Do you upload products?', 'Yes. Packages include product upload up to the listed quantity.'],
    ],
    relatedRoutes: ['product:website-design', 'product:wordpress-hosting', 'product:ssl-certificates', 'product:digital-marketing'],
  },

  // ── SEO & Marketing ────────────────────────────────────────
  'product:seo-services': {
    group: 'marketing',
    icon: 'TrendingUp',
    path: '/marketing/seo-services',
    breadcrumbLabel: 'SEO Services',
    navDesc: 'Rank higher on Google, get more leads',
    eyebrow: 'SEO SERVICES',
    heading: 'SEO that brings customers, not just traffic',
    summary: 'Technical SEO, on-page optimisation, local SEO and content that help your business rank for the searches your customers actually make — with clear monthly reporting.',
    title: 'SEO Services India – Technical, Local & On-Page SEO | Zexton',
    description: 'Monthly SEO services for Indian businesses: SEO audit, keyword research, on-page and technical SEO, Google Business Profile, content and link building.',
    searchIntent: 'SEO services India',
    topics: ['SEO services India', 'local SEO', 'technical SEO', 'SEO audit', 'Google Business Profile'],
    plans: [
      { name: 'Local SEO', tag: 'Local businesses', price: 7999, unit: '/mo', features: ['Google Business Profile optimisation', '10 target keywords', 'Local citations', 'On-page SEO (5 pages)', 'Review strategy', 'Monthly report'] },
      { name: 'Growth SEO', tag: 'Growing businesses', price: 14999, unit: '/mo', popular: true, features: ['Full SEO audit', '25 target keywords', 'Technical SEO fixes', 'On-page SEO (15 pages)', '2 blog articles / month', 'Quality link building', 'Monthly report & call'] },
      { name: 'Enterprise SEO', tag: 'Competitive markets', price: 29999, unit: '/mo', features: ['50+ target keywords', 'Competitor analysis', 'Content strategy', '4 articles / month', 'Digital PR & links', 'Core Web Vitals work', 'Dedicated SEO manager'] },
    ],
    features: [
      ['SEO audit', 'Crawl errors, speed, indexing, schema and content gaps identified and prioritised.'],
      ['Keyword research', 'Target the searches with real buying intent in your market.'],
      ['Local SEO', 'Show up in Google Maps and “near me” searches.'],
      ['Transparent reporting', 'Rankings, traffic, leads and work completed every month.'],
    ],
    faqs: [
      ['How long does SEO take?', 'Most sites see measurable movement in 3–6 months. Competitive keywords can take longer. We report progress monthly.'],
      ['Do you guarantee #1 rankings?', 'No honest agency can — Google controls rankings. We commit to proven work, transparency and measurable improvement.'],
      ['Is there a lock-in contract?', 'We recommend at least 6 months to see results, but plans are billed monthly.'],
    ],
    relatedRoutes: ['product:digital-marketing', 'product:website-design', 'product:web-hosting', 'insights'],
  },
  'product:digital-marketing': {
    group: 'marketing',
    icon: 'Megaphone',
    path: '/marketing/digital-marketing',
    breadcrumbLabel: 'Digital Marketing',
    navDesc: 'Google Ads, Meta ads & social media',
    eyebrow: 'DIGITAL MARKETING',
    heading: 'Performance marketing that turns ad spend into revenue',
    summary: 'Google Ads, Facebook & Instagram ads, LinkedIn campaigns and social media management — planned around leads and sales, tracked end to end.',
    title: 'Digital Marketing Agency India – Google Ads & Social Media | Zexton',
    description: 'Digital marketing services: Google Ads, Meta (Facebook & Instagram) ads, LinkedIn ads, social media management, email marketing and conversion tracking.',
    searchIntent: 'digital marketing agency India',
    topics: ['digital marketing agency', 'Google Ads management', 'social media marketing', 'Facebook ads'],
    plans: [
      { name: 'Social Starter', tag: 'Social media', price: 9999, unit: '/mo', features: ['2 platforms managed', '12 posts / month', 'Creative design', 'Caption & hashtag strategy', 'Monthly report'] },
      { name: 'Ads Growth', tag: 'Google + Meta ads', price: 14999, unit: '/mo', popular: true, note: 'Ad spend billed separately', features: ['Google & Meta ad management', 'Conversion tracking setup', 'Landing page advice', 'A/B creative testing', 'Weekly optimisation', 'Monthly performance call'] },
      { name: 'Full Funnel', tag: 'Ads + social + email', price: 29999, unit: '/mo', note: 'Ad spend billed separately', features: ['Everything in Ads Growth', '3 social platforms', 'Email marketing campaigns', 'Retargeting funnels', 'Dedicated marketing manager'] },
    ],
    features: [
      ['Google Ads', 'Search, Performance Max, YouTube and shopping campaigns.'],
      ['Meta ads', 'Facebook and Instagram campaigns targeted by interest and lookalikes.'],
      ['Social media', 'Consistent posting with on-brand creatives.'],
      ['Measured results', 'Conversion tracking so every rupee is accountable.'],
    ],
    faqs: [
      ['Is ad spend included?', 'No. Ad spend is paid directly to Google/Meta so you keep full control; our fee covers management.'],
      ['What budget should I start with?', 'Many local businesses start with ₹15,000–₹30,000 per month in ad spend and scale what works.'],
    ],
    relatedRoutes: ['product:seo-services', 'product:website-design', 'product:ecommerce-website', 'contact'],
  },
};

// Extra entries shown in the "Services" mega-menu column (existing software services + IT).
export const extraServiceLinks = [
  ['service:web-application-development', 'Web Applications'],
  ['service:custom-software-development', 'Custom Software'],
  ['service:saas-development', 'SaaS Development'],
  ['service:mobile-app-development', 'Mobile Apps'],
  ['service:ai-automation', 'AI Automation & Chatbots'],
  ['service:cloud-modernization', 'Cloud & DevOps'],
  ['service:it-support', 'IT Support & Server Management'],
];

export const productRouteMetadata = Object.fromEntries(
  Object.entries(productPages).map(([route, page]) => [route, {
    ...page,
    schemaType: 'WebPage',
    itemType: 'Product',
    relatedRoutes: page.relatedRoutes,
    schemaItems: [{ type: 'Service', name: page.breadcrumbLabel, description: page.description, path: page.path }],
    crawlSections: [
      { title: page.heading, text: page.summary },
      ...(page.plans || []).map((plan) => ({ title: `${plan.name} — ${inr(plan.price)}${plan.unit}`, text: plan.features.join(', ') })),
      ...page.features.map(([title, text]) => ({ title, text })),
      ...page.faqs.map(([title, text]) => ({ title, text })),
    ],
  }]),
);

export const productsInGroup = (groupId) => Object.entries(productPages)
  .filter(([, page]) => page.group === groupId)
  .map(([route, page]) => ({ route, ...page }));

export const lowestPrice = (page) => page.priceFrom ?? Math.min(...(page.plans || []).map((plan) => plan.price));
