export const servicePages = {
  'service:custom-software-development': {
    path: '/services/custom-software-development',
    breadcrumbLabel: 'Custom Software Development',
    eyebrow: 'CUSTOM SOFTWARE DEVELOPMENT',
    heading: 'Custom software built around the way your business works',
    summary: 'Design and engineer secure business applications, customer platforms, internal systems, portals, and integrations around real users, rules, and operating constraints.',
    title: 'Custom Software Development Company in India | Zexton',
    description: 'Custom software development for business applications, portals, workflow systems, integrations, modernization, and secure cloud delivery from Zexton.',
    searchIntent: 'custom software development company India',
    topics: ['custom software development company', 'business application development', 'enterprise software development', 'software integration services', 'custom application development India'],
    challenge: 'Off-the-shelf software becomes expensive when teams must bend critical workflows around generic assumptions, duplicate data between systems, or rely on manual exceptions.',
    outcome: 'A maintainable application that reflects the actual workflow, permissions, decisions, integrations, reporting needs, and operational ownership of the business.',
    goodFor: ['Customer and partner portals', 'Internal operations and approval systems', 'Workflow automation and system integration', 'Legacy application replacement', 'Data-heavy dashboards and reporting'],
    deliverables: ['Workflow and requirements discovery', 'UX architecture and interface design', 'Frontend, backend, APIs, and integrations', 'Identity, roles, auditability, and security controls', 'Cloud deployment, monitoring, documentation, and handover'],
    process: [
      ['Discover', 'Map users, current work, exceptions, data, integrations, risks, and measurable outcomes.'],
      ['Design', 'Define the product boundary, experience, architecture, delivery milestones, and acceptance criteria.'],
      ['Build', 'Deliver reviewable vertical slices with engineering, quality, security, and deployment considered together.'],
      ['Operate', 'Launch with monitoring, recovery, documentation, ownership, and a clear improvement path.'],
    ],
    faqs: [
      ['What makes custom software different from a packaged tool?', 'Custom software is designed for your workflows, rules, integrations, roles, and operating context rather than requiring the business to adopt a generic product model.'],
      ['Can Zexton modernize an existing system?', 'Yes. Modernization can be incremental: stabilize the current system, expose interfaces, move selected workflows, migrate data carefully, and retire risk in controlled stages.'],
      ['How is a custom software project estimated?', 'The estimate depends on workflow complexity, user roles, integrations, data migration, security, content readiness, quality requirements, and delivery timing. Discovery reduces uncertainty before a larger commitment.'],
    ],
    relatedRoutes: ['services', 'service:web-application-development', 'service:cloud-modernization', 'pricing'],
  },
  'service:saas-development': {
    path: '/services/saas-development',
    breadcrumbLabel: 'SaaS Development',
    eyebrow: 'SAAS PRODUCT ENGINEERING',
    heading: 'SaaS product development from first workflow to reliable platform',
    summary: 'Plan, build, launch, and evolve multi-tenant SaaS products with secure identity, subscriptions, administration, analytics, and cloud operations.',
    title: 'SaaS Development Company & Product Engineering | Zexton',
    description: 'End-to-end SaaS development for MVPs and growing platforms: product discovery, multi-tenancy, billing, RBAC, analytics, integrations, and cloud delivery.',
    searchIntent: 'SaaS development company',
    topics: ['SaaS development company', 'SaaS MVP development', 'multi-tenant SaaS architecture', 'SaaS product engineering', 'subscription software development'],
    challenge: 'A SaaS product is more than a feature set. Tenant isolation, onboarding, roles, billing, plan limits, administration, support, observability, and change management must work as one operating system.',
    outcome: 'A focused SaaS release with a credible product boundary and foundations that can evolve without prematurely building enterprise complexity.',
    goodFor: ['B2B SaaS MVPs', 'Multi-tenant workflow products', 'Subscription platforms', 'Vertical SaaS for specific industries', 'Existing SaaS architecture and reliability improvements'],
    deliverables: ['Product discovery and MVP definition', 'Tenant, team, role, and permission model', 'Subscription, entitlement, and usage workflows', 'Administration, notifications, analytics, and integrations', 'Cloud delivery, observability, backups, and support tooling'],
    process: [
      ['Validate', 'Define the user, painful workflow, adoption path, value signal, and smallest useful release.'],
      ['Model', 'Design tenancy, identity, permissions, plans, data boundaries, and operational controls.'],
      ['Deliver', 'Ship complete workflows in milestones, including administration and production behavior.'],
      ['Evolve', 'Use product and operational evidence to improve activation, reliability, performance, and roadmap decisions.'],
    ],
    faqs: [
      ['Can Zexton build a SaaS MVP?', 'Yes. The MVP is defined around a complete valuable workflow and credible production operation, not simply the fewest screens.'],
      ['How do you approach multi-tenancy?', 'The model depends on isolation, compliance, scale, customization, and cost needs. Tenant context is enforced through identity, authorization, data access, testing, and observability.'],
      ['Can you improve an existing SaaS platform?', 'Yes. Work can focus on architecture, onboarding, billing, administration, performance, reliability, security, or a specific roadmap area without requiring a full rebuild.'],
    ],
    relatedRoutes: ['services', 'service:custom-software-development', 'service:cloud-modernization', 'pricing'],
  },
  'service:web-application-development': {
    path: '/services/web-application-development',
    breadcrumbLabel: 'Web Application Development',
    eyebrow: 'WEB APPLICATION DEVELOPMENT',
    heading: 'Fast, accessible web applications engineered for real workflows',
    summary: 'Build responsive portals, dashboards, marketplaces, commerce experiences, and operational web applications with secure APIs and dependable cloud foundations.',
    title: 'Web Application Development Company | React & APIs | Zexton',
    description: 'Web application development for portals, dashboards, marketplaces, commerce, and operations using React, secure APIs, integrations, and cloud delivery.',
    searchIntent: 'web application development company',
    topics: ['web application development company', 'React development company', 'business web app development', 'portal development', 'dashboard development'],
    challenge: 'Business web applications fail when interface polish is separated from workflow logic, data quality, permissions, accessibility, performance, and production operations.',
    outcome: 'A responsive web product where the interface, APIs, data model, security, integrations, analytics, and operational behavior support one coherent user journey.',
    goodFor: ['Customer self-service portals', 'Operational dashboards and internal tools', 'Marketplaces and commerce workflows', 'Partner and vendor platforms', 'Data and reporting applications'],
    deliverables: ['Responsive UX and reusable interface system', 'React frontend and typed application architecture', 'Secure backend APIs and data models', 'Authentication, permissions, payments, and integrations', 'Performance, accessibility, analytics, testing, and deployment'],
    process: [
      ['Frame', 'Identify the users, critical journeys, content, business rules, systems, and success measures.'],
      ['Prototype', 'Make information architecture and important interactions testable before implementation expands.'],
      ['Engineer', 'Build frontend and backend workflows together with automated quality and security checks.'],
      ['Optimize', 'Measure real performance, usability, reliability, and conversion or completion behavior after launch.'],
    ],
    faqs: [
      ['Which web technologies does Zexton use?', 'Technology is selected for the product context. Common capabilities include React, TypeScript, Node.js, .NET, Python, PostgreSQL, APIs, and AWS.'],
      ['Do you build both frontend and backend?', 'Yes. Web application delivery can cover product design, frontend, backend, data, integrations, testing, cloud deployment, monitoring, and handover.'],
      ['Will the application be mobile responsive and accessible?', 'Responsive behavior and semantic accessibility are planned as core product quality. The appropriate conformance and testing depth is agreed from the user and regulatory context.'],
    ],
    relatedRoutes: ['services', 'service:custom-software-development', 'service:mobile-app-development', 'capabilities'],
  },
  'service:mobile-app-development': {
    path: '/services/mobile-app-development',
    breadcrumbLabel: 'Mobile App Development',
    eyebrow: 'MOBILE APP DEVELOPMENT',
    heading: 'React Native mobile products designed beyond the screen',
    summary: 'Create cross-platform mobile applications with secure APIs, offline behavior, native capabilities, notifications, analytics, and release-ready operations.',
    title: 'React Native Mobile App Development Company | Zexton',
    description: 'React Native mobile app development for Android and cross-platform products with secure APIs, offline workflows, notifications, analytics, and releases.',
    searchIntent: 'React Native app development company India',
    topics: ['React Native development company', 'mobile app development India', 'cross-platform app development', 'Android app development', 'mobile product engineering'],
    challenge: 'Mobile quality depends on more than matching desktop screens. Connectivity, device permissions, interruptions, offline state, notifications, security, performance, and store operations shape the experience.',
    outcome: 'A focused mobile product with clear journeys, resilient data behavior, appropriate native integration, release discipline, and measurable operating quality.',
    goodFor: ['Customer and field-service applications', 'Companion apps for SaaS platforms', 'Offline and intermittent-connectivity workflows', 'Mobile commerce and service booking', 'Existing React Native product improvement'],
    deliverables: ['Mobile journey and interaction design', 'React Native application engineering', 'Secure APIs, authentication, and local data', 'Notifications, deep links, camera, location, and other native capabilities', 'Testing, analytics, release preparation, and production monitoring'],
    process: [
      ['Prioritize', 'Define the mobile moments that create value and which capabilities truly need a device experience.'],
      ['Design', 'Plan navigation, state, interruption recovery, permissions, accessibility, and offline behavior.'],
      ['Integrate', 'Build the application and secure API contract together, including native services and analytics.'],
      ['Release', 'Test on representative devices, prepare store assets, manage rollout, monitor quality, and improve.'],
    ],
    faqs: [
      ['Why use React Native?', 'React Native can share product logic and engineering capability across platforms while retaining access to native features. It is selected only when its trade-offs fit the product.'],
      ['Can the app work offline?', 'Yes, where the workflow requires it. Offline support needs explicit rules for local storage, synchronization, conflicts, security, and user feedback.'],
      ['Do you help with app-store release?', 'Release support can include build configuration, signing, store assets, privacy inputs, testing tracks, staged rollout, crash monitoring, and update planning.'],
    ],
    relatedRoutes: ['services', 'service:web-application-development', 'service:cloud-modernization', 'pricing'],
  },
  'service:ai-automation': {
    path: '/services/ai-automation',
    breadcrumbLabel: 'AI Automation',
    eyebrow: 'AI AUTOMATION & AGENTS',
    heading: 'Responsible AI automation connected to measurable work',
    summary: 'Design model-powered workflows, retrieval systems, assistants, and agents with evaluation, approved tools, human controls, privacy, and operational visibility.',
    title: 'AI Automation & AI Agent Development Services | Zexton',
    description: 'AI automation and agent development for business workflows using retrieval, tool integration, evaluation, guardrails, human approval, and observability.',
    searchIntent: 'AI automation company India',
    topics: ['AI automation services', 'AI agent development company', 'RAG development', 'business process AI automation', 'generative AI integration'],
    challenge: 'An impressive model demo is not a dependable business system. The task, source data, tools, permissions, evaluation, failure handling, cost, privacy, and human accountability must be designed explicitly.',
    outcome: 'A bounded AI-enabled workflow with measurable quality, traceable inputs and actions, clear escalation, and ownership when the system is uncertain or wrong.',
    goodFor: ['Knowledge retrieval and grounded assistants', 'Document classification and extraction', 'Human-reviewed drafting and decision support', 'Tool-using workflow agents', 'AI opportunity and readiness assessment'],
    deliverables: ['Workflow and AI readiness assessment', 'Data, retrieval, prompt, and tool architecture', 'Evaluation datasets and quality criteria', 'Permissions, guardrails, human approval, and auditability', 'Monitoring for quality, latency, cost, and failures'],
    process: [
      ['Choose', 'Select a frequent, measurable, bounded workflow where model capability can create real value.'],
      ['Evaluate', 'Establish representative examples and acceptance criteria before optimizing prompts or models.'],
      ['Control', 'Connect approved data and tools with least privilege, validation, human review, and fallbacks.'],
      ['Observe', 'Track quality, exceptions, latency, cost, user behavior, and changes in model or data performance.'],
    ],
    faqs: [
      ['What is a good first AI automation project?', 'A good candidate is frequent, time-consuming, bounded, supported by accessible data, and easy to evaluate against a current process.'],
      ['Do you build AI agents?', 'Yes, when an agent is appropriate. The design limits available tools and permissions, validates actions, records traces, and requires human approval for consequential steps.'],
      ['How do you reduce hallucinations?', 'Risk is reduced through grounded retrieval, structured outputs, constrained tools, validation, evaluation, uncertainty handling, citations where useful, and human review. It cannot be solved by a single prompt.'],
    ],
    relatedRoutes: ['services', 'capabilities', 'insights', 'contact'],
  },
  'service:cloud-modernization': {
    path: '/services/cloud-devops-modernization',
    breadcrumbLabel: 'Cloud, DevOps & Modernization',
    eyebrow: 'CLOUD, DEVOPS & MODERNIZATION',
    heading: 'Modernize software safely while the business keeps moving',
    summary: 'Improve cloud infrastructure, deployment, observability, security, resilience, performance, and legacy systems through controlled, evidence-based change.',
    title: 'Cloud, DevOps & Legacy Modernization Services | Zexton',
    description: 'Cloud, DevOps, and legacy modernization services covering AWS, CI/CD, containers, observability, security, resilience, performance, and migration.',
    searchIntent: 'legacy software modernization company',
    topics: ['legacy software modernization', 'cloud modernization services', 'DevOps consulting India', 'AWS cloud engineering', 'application modernization company'],
    challenge: 'Legacy systems often carry critical business knowledge. Replacing them all at once can convert technical debt into operational risk, while avoiding change allows reliability and delivery constraints to grow.',
    outcome: 'A staged modernization path that protects critical workflows, improves production visibility, reduces deployment risk, and creates room for product change.',
    goodFor: ['Legacy web and business applications', 'Manual or fragile deployment processes', 'Cloud migration and infrastructure improvement', 'Reliability, performance, and cost problems', 'Security, backup, and recovery gaps'],
    deliverables: ['System, dependency, and operational risk assessment', 'Target architecture and staged migration roadmap', 'Cloud infrastructure and deployment automation', 'Monitoring, logging, alerting, backup, and recovery', 'Security hardening, performance work, documentation, and handover'],
    process: [
      ['Understand', 'Map critical workflows, dependencies, data, failure modes, release constraints, and business risk.'],
      ['Stabilize', 'Improve observability, recovery, repeatability, tests, and interfaces before major structural change.'],
      ['Separate', 'Move bounded capabilities behind stable contracts and migrate traffic or data in controlled stages.'],
      ['Retire', 'Remove old paths only after verification, operational readiness, ownership, and rollback confidence.'],
    ],
    faqs: [
      ['Does modernization require a full rewrite?', 'Usually not. Incremental modernization can reduce risk by stabilizing the current system and replacing bounded capabilities in priority order.'],
      ['Can you improve CI/CD and cloud operations?', 'Yes. Work can include build and deployment automation, environments, infrastructure, secrets, observability, backups, recovery, performance, and cost visibility.'],
      ['How do you reduce migration risk?', 'Use explicit dependency mapping, production baselines, automated checks, staged data movement, compatibility layers, controlled rollout, monitoring, and tested rollback paths.'],
    ],
    relatedRoutes: ['services', 'service:custom-software-development', 'service:saas-development', 'capabilities'],
  },
};

export const serviceRouteMetadata = Object.fromEntries(
  Object.entries(servicePages).map(([route, page]) => [route, {
    ...page,
    schemaType: 'WebPage',
    itemType: 'Service',
    schemaItems: [{ type: 'Service', name: page.breadcrumbLabel, description: page.description, path: page.path }],
    crawlSections: [
      { title: page.heading, text: page.summary },
      { title: 'The business problem', text: page.challenge },
      { title: 'The intended outcome', text: page.outcome },
      ...page.process.map(([title, text]) => ({ title, text })),
      ...page.faqs.map(([title, text]) => ({ title, text })),
    ],
  }]),
);
